name: Pull Request Title Check
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
jobs:
  check_pr_title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_configuration_owner: 'krogerco'
          github_configuration_repo: 'Shared-CI-Workflow-Android'
          github_configuration_path: '.github/config/pr-title-checker-config.json'
          github_configuration_ref: 'v1.0.0'
